export const CREATE_PROFILE = 'CREATE_PROFILE';
export const GET_PROFILE = 'GET_PROFILE';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const GET_ALL_PROFILES = 'GET_ALL_PROFILES';
export const INVITE_PROFILE_TO_WATCHLIST = 'INVITE_PROFILE_TO_WATCHLIST';
