export const SET_WATCHLIST_TEXT_FILTER = 'SET_WATCHLIST_TEXT_FILTER';
export const SET_WATCHLIST_GENRE_FILTER = 'SET_WATCHLIST_GENRE_FILTER';
export const SET_WATCHLIST_MEDIA_FILTER = 'SET_WATCHLIST_MEDIA_FILTER';
